export enum RouteName {
  DASHBOARD = 'DASHBOARD',
  SPLINE_CORRECTION = 'SPLINE_CORRECTION',
  BINARIZATION_QUANTIZATION = 'BINARIZATION_QUANTIZATION',
  MORPHOLOGY = 'MORPHOLOGY',
  SPATIAL_FILTERING = 'SPATIAL_FILTERING',
}
